[gcp_service_account]
type = "service_account"
project_id = "streamlit-gsheet-access-467210"
private_key_id = "125b6288ebaf1952f426cfb82ca9cfb740412b28"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2RKErZ0A373Ky
wvloDYymjYv9i67Z5YezK6uJJH4W55CHSQyOzkvUVljtqmdBJ4Tu3XxgDFaAPAWW
1QKahpyCw359HJEW3ZvyV+Li/0YymwbAqXvp9mHJthh81J05bQE59xIySftAWP0j
Ns/a7FP/DsK6Q3lyjHeix++yRUZep/TZ29UiPkAhE2/Asa+ALwxwKoioKvc6MVay
HRQQaFlI/BXMKWoN5tpT8FMJjY2m7c26WdzJjTnPQrvGORCo9fgu4aeY3JuPa7Av
Mq5m6jL8Ihx+cxuKBcLw0rqRJJA1gQFvnMS+2HOsk1VM/g/8QvjZTSYUaQ8fEsl4
AAX5QVDTAgMBAAECggEAER/cOe+2y4qRBCqStCv8YvQ5itYXf3FekSmGhu60H1gc
7sOg4mnkxfZhid17W1ZohD4Fnss0n/0DqWrUlnVp5FSUYGd8BOHynOTqSYQiXEQk
cPAmLD0cbY8mOH7hUVvkbvBqTT9A092IgEkjY4uAo3Nc6D3JU0cklllNM+U+T0uK
KDVRjCK1ojIX7WWKYl2NDeA8rjAQ98WfSRusDxtLSAkRiS7QavV+J21CXuSPJ5Vt
MkPc8JejBiqyeEAkPU7mf+w3h7BAxlWXRbqEYi4g/Yxi9NdhBHtc7O7ZRzJUfnTy
FvGtNYUTjXEDemecvnGL80Tq0Wzflr7AJ2czI8+CwQKBgQD1O1Zlw7NHPIRClRQV
gTb/DaDYGAxyhwh1CteXIp82bSB7T0lX2gyVgXEVxvL2tYZ35qozO2lb+qzgrDWd
kr//y/2/KtYkyQFYeizg7FgSuQXRIOinWAGr4qoGRgTocMlVb/Fo9nYCKiRWrpY7
epznkboNAq7zpyo8f43I5m/xjQKBgQC+RYOWjpg0ASzbXn/luXSx4phURfiiwKI2
hapjF2OXImmQMbDGEliBCsnHyVskWjUiSPFxDDs4gMBK9VFQ0qvHNW5obwg3+GAF
MTvuNkfuxZpxrPAZrOZt2sen9QyLBS8q5QPFecsPgZQZFegIJF3m8tVd/R4uYz6h
x7Cp7x5D3wKBgEgH/96wVw6LlgXAqD+QzsioBiCzH6TcSP2oC59XChEAiNPvfAmU
ALJBbSgKYf9ZXoAFfuTBhLcBsJnlu3HnUwIdtxDZ0kDH0d9dM6V1hoEpW64Lzoqo
7QTB9VMWagakal7wHKbKDeug2T+k1HfwEfpq8Y00xpLG/T778HecSDFZAoGBAK6j
7UCuhyMMhRigpzG6xFJV0k1fn/P6bakvjJHBMQbSbiQMh911j0h6F3TJ6171cVmT
rBCAEoctHdJvUoClrUd+UmWGq/t7fN6nLwPZTLLrKnP2MLbQTPw92A3gTO/5BS8Q
3yJNRMVpwP45biyy/IFzF8ZaAm6/Zwhk2lFPie7vAoGBAL/r30ZBewUN27db4qgs
Av5EHrTgcNRvjTR09PbDJkCs4gjU8yHja1dN6QaH4E+wC1i7EYPe9wvOFRw7KD0u
4B2Giu3m/AinTEwiQ9FVG6QQfxuhq3G+T+CLGQkFeLIuqBbFrp54vKy+stVOMoEb
mPGv+ZfmkfHEp/Xoe5PmX5cj
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@streamlit-gsheet-access-467210.iam.gserviceaccount.com"
client_id = "115787242337396555353"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40streamlit-gsheet-access-467210.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
